### ISSUE TITLE
Doesn't seem to work in DF

### ISSUE THREAD

**Issue by WanderingFox** [NumyAddon/BlizzMovePlugin_Rematch#1]
Latest Blizzmove (v3.5.2) and latest Rematch (v4.14.4). No errors but the frame is not draggable.

**Comment by Numynum** [comment]
hi, are you talking about this frame, or some other frame?
![image](https://user-images.githubusercontent.com/17293527/199354347-72760263-faf0-46c6-a2aa-3f9e1c7f4c18.png)

**Comment by WanderingFox** [comment]
Correct the main pet journal frame. Collections tab moves normally with any other tab open (thanks to blizzmove), but the will not move with the pet journal open even though blizzmoveplugin_rematch is loading and running with no errors.

**Comment by Numynum** [comment]
very strange, it's working fine for me 🤔 
is this also happening when you have no addons loaded except blizzmove, rematch, and this plugin?

**Comment by WanderingFox** [comment]
Huh apparently Rarity is touching the pet frame in some way that's breaking it. That's... really bizarre. Apologies for the false alarm!

**Comment by Numynum** [comment]
No worries, good to know what caused it :)

**Comment by brett1337** [comment]
I can confirm that rarity is causing this addon to not function. I will link this issue in the rarity repo. 

Unless it is possible to fix it through this addon?

**Comment by Numynum** [comment]
decided to look into it a bit more; and it seems to be an interesting interaction of
1.  Rematch removing all hooks, and setting their handlers for MouseDown roughly when the loading screen ends (`PLAYER_ENTERING_WORLD`)
2. BlizzMove hooking MouseDown when Blizzard_Collections addon loads

this usually goes fine, because the Blizzard_Collections addon doesn't load until you open the UI, so Rematch sets up their stuff, and then BlizzMove does their thing afterwards, all good 👌
but then, when Rarity is enabled
1. Rarity force loads the Blizzard_Collections addon before `PLAYER_ENTERING_WORLD`
2. BlizzMove hooks MouseDown (because the addon is loaded; before `PLAYER_ENTERING_WORLD`)
4. Rematch nukes all hooks, when it finally loads, after `PLAYER_ENTERING_WORLD`

which leaves it in an immovable state 🙁

to be honest, this is something that's mostly caused by Rematch loading their things at an odd timing, and nuking all handlers, instead of simply adding their own (which is usually fine, since it's their own frames; but it does break plugins like mine)
I'm thinking of creating a workaround to detect and restore BlizzMove's handlers whenever an addon tries to nuke them

(I'll post this in the issue on Rarity too)

**Comment by Numynum** [comment]
should be fixed with next blizzmove version

**Comment by Knaledge** [comment]
I can confirm that PetBattleMaster also breaks this plugin when simply loaded alongside Rematch. Disabling PetBattleMaster allows the Pet Journal (Rematch and standard UI variants) to move once more with this plugin enabled.
